### ISSUE TITLE
Emptying a date field interaction

### ISSUE THREAD

**Issue by thvu11** [nathanreyes/v-calendar#1270]
Congrats on the big milestone of releasing the office v3.0.0.

When I play with the new documentation, I realise that if I want to deselect a date option, I have to manually do it via the popup calendar. If I try to clear it by clicking `Backspace` on keyboard. It throws an invalid error.

Is it an expected behavior?

https://vcalendar.io/datepicker/slot-content.html#input-element

<img width="640" alt="image" src="https://user-images.githubusercontent.com/17879893/225527409-c69b7bd4-2d6d-46f7-92b3-5ae8a4a42019.png">

Step to replicate:
- highlight the input value and clear it via `Backspace`

**Comment by JosePerez27** [comment]
I have the same problem in my app!

**Comment by nathanreyes** [comment]
Fixed in 3.0.2.

**Comment by mdoesburg** [comment]
@nathanreyes 

> Fixed in 3.0.2.

Still an issue when using `v-model.range="range"`. (using version v3.0.3)
