### ISSUE TITLE
Failed to compile on v3

### ISSUE THREAD

**Issue by mrquokka** [nathanreyes/v-calendar#1271]
After upgrade build crushed

```
-  Building for production...
 ERROR  Failed to compile with 1 error03:48:10

 error  in ./node_modules/v-calendar/dist/es/index.js

Module parse failed: Unexpected token (1809:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const resolveEl = (target) => {
|   if (target == null)
>     return target ?? null;
|   if (document && isString_1(target))
|     return document.querySelector(target);

 @ ./node_modules/cache-loader/dist/cjs.js!./node_modules/vue-cli-plugin-coffee/node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/coffee-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--1-1!./src/components/date_picker.vue?vue&type=script&lang=coffee 2:0-40 7:17-27
 @ ./src/components/date_picker.vue?vue&type=script&lang=coffee
 @ ./src/components/date_picker.vue
 @ ./node_modules/cache-loader/dist/cjs.js!./node_modules/vue-cli-plugin-coffee/node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/coffee-loader/dist/cjs.js!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--1-1!./src/App.vue?vue&type=script&lang=coffee
 @ ./src/App.vue?vue&type=script&lang=coffee
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js ./src/add_metrics.js
```

**Comment by Jebasuthan** [comment]
> After upgrade build crushed

@mrquokka I am also facing the same issue. Any luck?

**Comment by crodrigueza16** [comment]
Same with node 14.21.3

**Comment by mrquokka** [comment]
> > After upgrade build crushed
> 
> @mrquokka I am also facing the same issue. Any luck?

i think that problems is Nullish_coalescing (??) - i can try to change node ver/babel versions

**Comment by ioannisgiannis** [comment]
Hello,

Same issue for me.
After upgrading from v3.0.0 to v3.0.1 the npm install failed.
vue.js: v3.2.47
node.js: v16.19.0

Screenshot of the error:
![image](https://user-images.githubusercontent.com/46316269/225865917-136232d3-170e-4dc4-92db-844e4de2b903.png)

**Comment by mrquokka** [comment]
Solved by upgrade to vue-cli 5.* versions instead of 4.5.*
(remember, you may need this fix https://github.com/vuejs/vue-cli/issues/6785)

**Comment by kovelo** [comment]
Same issue here, it is definitely due to the nullish-coalescing-operator. Adding that plugin to my babel configuration does not fix the issue though.

**Comment by kovelo** [comment]
Update, I have fixed this...

1. Install @babel/plugin-proposal-nullish-coalescing-operator as a dev dependency
2. Update babel.config.js and add it as a plugin, here is my babel.config
```js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
 plugins: [
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-private-methods',
    '@babel/plugin-proposal-nullish-coalescing-operator'
  ]
}
```
3. Update vue.config.js to transpile the v-calendar dependency, here is the relevant part
```js
module.exports = {
  transpileDependencies: [
    'v-calendar'
  ]
}
```

That should solve this issue.

**Comment by novaloktavio** [comment]
tst
